//nmcli

//

nmcli connection show eht-enp0s8 | grep ipv4

nmcli connection show
nmcli connection modify WIREDCONNECTION\ 1 connection.id eth-enp0s8
nmcli connection show

nmcli -f NAME,DEVICE connection
nmcli -f NAME,DEVICE,TIMESTAMP-REAL,AUTO CONNECT c

nmcli general hostname wbcentos7
hostname
nmcli general hostname centos7
hostname


nmcli general loggin level DEBUG domains IP4
journalctl -f



nmcli connection modify eth-enp0s8 ipv4.method manual
nmcli connection modify eth-emp0s8 ipv4.addresses "10.10.0.14/24 10.10.0.1"
nmcli connection down eth-enp0s8
nmcli connection up eth-enp0s8
nmcli connection down eth-enp0s8 ; nmcli connection up eth-enp0s8



nmcli connection modify eth-enp0s8 ipv4.dns "10.0.0.1 10.0.0.2"
nmcli connection modify eth-enp0s8 ipv4.dns-search "ex.com"
nmcli connection down eth-enp0s8
nmcli connection up eth-enp0s8
cat /etc/resolv.conf
Generated by NetworkManager



nmcli connection modify enp0s8 connection.autoconnect yes


nmcli connection
nmcli connection show WIREDCONNECTION\ 1 | grep autoconnect
nmcli connection modify WIRECONNECTION\ 1 connection.autoconnection false
nmcli connection show WIRECONNECTION\ 1 | grep auto connect
nmcli connection down WIRECONNECTION\ 1
nmcli connection show --active
nmcli connection up WIRECONNECTION\ 1


nmcli network off
nmcli network on

nmcli connection down eth-enp0s8
nmcli connection up eth-enp0s8

nmcli dev show wlan0





---

